name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      #----------------------------------------------
      #        load pip cache if cache exists
      #----------------------------------------------
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      #----------------------------------------------
      #          install and run linters
      #----------------------------------------------
      - run: python -m pip install black flake8 isort
      - run: |
          flake8 . --count --show-source --statistics
          black . --check
          isort .

  test:
    needs: linting
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ['3.11']
    runs-on: ${{ matrix.os }}
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PostgreSQL Development Tools (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Install PostgreSQL (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install postgresql

      - name: Install PostgreSQL (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install postgresql --yes --no-progress

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          source .venv/bin/activate
          pytest tests/

      - name: Run tests (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          source .venv/bin/activate
          pytest tests/

      - name: Run tests (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          call .venv\Scripts\activate
          pytest tests/
